import dotenv from 'dotenv';

dotenv.config({ path: './.env' });

export const config = {
	NODE_ENV: process.env.NODE_ENV ?? 'development',
	PORT: process.env.PORT,
	ALLOWED_CLICKS: process.env.ALLOWED_CLICKS,
	BASE_URL: process.env.BASE_URL,
	USERNAME: process.env.USERNAME,
	PASS: process.env.PASS,
	URL_SHORTNER_FB_TYPE: process.env.URL_SHORTNER_FB_TYPE,
	URL_SHORTNER_FB_PROJECT_ID: process.env.URL_SHORTNER_FB_PROJECT_ID,
	URL_SHORTNER_FB_PRIVATE_KEY_ID: process.env.URL_SHORTNER_FB_PRIVATE_KEY_ID,
	URL_SHORTNER_FB_PRIVATE_KEY: process.env.URL_SHORTNER_FB_PRIVATE_KEY,
	URL_SHORTNER_FB_CLIENT_EMAIL: process.env.URL_SHORTNER_FB_CLIENT_EMAIL,
	URL_SHORTNER_FB_CLIENT_ID: process.env.URL_SHORTNER_FB_CLIENT_ID,
	URL_SHORTNER_FB_AUTH_URI: process.env.URL_SHORTNER_FB_AUTH_URI,
	URL_SHORTNER_FB_TOKEN_URI: process.env.URL_SHORTNER_FB_TOKEN_URI,
	URL_SHORTNER_FB_AUTH_PROVIDER_X509_CERT_URL: process.env.URL_SHORTNER_FB_AUTH_PROVIDER_X509_CERT_URL,
	URL_SHORTNER_FB_CLIENT_X509_CERT_URL: process.env.URL_SHORTNER_FB_CLIENT_X509_CERT_URL
}